local config = require('nvpic.config')

describe('nvpic.config', function()
  before_each(function()
    config.reset()
  end)

  describe('defaults', function()
    it('returns default config when no overrides', function()
      local cfg = config.get()
      assert.equals('pics', cfg.pics_dir)
      assert.equals(1.0, cfg.default_scale)
      assert.is_true(cfg.auto_render)
      assert.equals(200, cfg.debounce_ms)
      assert.is_nil(cfg.protocol)
      assert.is_false(cfg.telescope)
    end)

    it('has default keymaps', function()
      local cfg = config.get()
      assert.equals('<leader>ip', cfg.keymaps.paste)
      assert.equals('<leader>if', cfg.keymaps.pick)
      assert.equals('<leader>it', cfg.keymaps.toggle)
      assert.equals('<leader>ir', cfg.keymaps.refresh)
    end)

    it('returns a copy from get', function()
      local cfg = config.get()
      cfg.keymaps.paste = '<leader>xx'

      local fresh = config.get()
      assert.equals('<leader>ip', fresh.keymaps.paste)
    end)
  end)

  describe('setup', function()
    it('merges user overrides with defaults', function()
      config.setup({ default_scale = 0.5, pics_dir = 'images' })
      local cfg = config.get()
      assert.equals(0.5, cfg.default_scale)
      assert.equals('images', cfg.pics_dir)
      assert.is_true(cfg.auto_render)
    end)

    it('deep merges keymaps', function()
      config.setup({ keymaps = { paste = '<leader>pp' } })
      local cfg = config.get()
      assert.equals('<leader>pp', cfg.keymaps.paste)
      assert.equals('<leader>if', cfg.keymaps.pick)
    end)

    it('allows disabling keymaps with false', function()
      config.setup({ keymaps = { paste = false } })
      local cfg = config.get()
      assert.is_false(cfg.keymaps.paste)
    end)

    it('rejects pics_dir values that traverse upward', function()
      local ok, err = pcall(function()
        config.setup({ pics_dir = '../outside' })
      end)

      assert.is_false(ok)
      assert.truthy(tostring(err):match('pics_dir'))
    end)

    it('rejects absolute pics_dir values', function()
      local ok, err = pcall(function()
        config.setup({ pics_dir = '/tmp/pics' })
      end)

      assert.is_false(ok)
      assert.truthy(tostring(err):match('pics_dir'))
    end)

    it('rejects invalid default_scale', function()
      assert.has_error(function()
        config.setup({ default_scale = 0 })
      end)
      assert.has_error(function()
        config.setup({ default_scale = -1 })
      end)
      assert.has_error(function()
        config.setup({ default_scale = 11 })
      end)
      assert.has_error(function()
        config.setup({ default_scale = 'big' })
      end)
    end)

    it('rejects invalid debounce_ms', function()
      assert.has_error(function()
        config.setup({ debounce_ms = -50 })
      end)
      assert.has_error(function()
        config.setup({ debounce_ms = 'fast' })
      end)
    end)

    it('accepts valid edge values', function()
      assert.has_no.errors(function()
        config.setup({ default_scale = 0.01, debounce_ms = 0 })
      end)
    end)
  end)

  describe('commentstring', function()
    it('returns default when buffer has no commentstring', function()
      local buf = vim.api.nvim_create_buf(false, true)
      local cs = config.commentstring(buf)
      assert.equals(config.DEFAULT_COMMENTSTRING, cs)
      vim.api.nvim_buf_delete(buf, { force = true })
    end)
  end)
end)
